name: CI
on:
  push:
    branches: [main]
  pull_request:
    types: ["opened", "edited", "synchronize"]
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@main
        with:
          deno-version: "v2.x"
      - name: Check Formatting
        run: deno fmt --check
